package:
    name: pfs-isochrones
    version: 0.1.14

source:
    path: ../

build:
    noarch: python
    number: 14
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - pfsiso-synthmag = pfs.ga.isochrones.scripts.synthmag:main
        - pfsiso-import = pfs.ga.isochrones.scripts.import_:main


requirements:
    build:
        - python >=3.7
        - setuptools >=65.0.2
        - setuptools_scm[toml]>=4
        - pip >=22.0

    run:
        - tqdm >=4.42.1
        - numpy >=1.18.5
        - pandas >=1.0.1
        - h5py >=2.10.0
        - matplotlib >=3.1.3
        - scipy >=1.5.3
        - tensorflow >=2.4


about:
    home: https://github.com/Subaru-PFS-GA/ga_isochrones
    license: NO LICENSE - DO NOT DISTRIBUTE